### PR TITLE
license: Add AGPLv3 license to project

### PR DESCRIPTION
**Pull request by cgmcintyr**
Make YouTubeMySpotify free as in freedom.

### CODE REVIEW

**Comment by cgmcintyr** [comment]
@theWebby

**Comment by cgmcintyr** [comment]
AGPL ensures that no cloud provider can create a product out of your code without contributing back to the original project

**Comment by theWebby** [comment]
Actually that does sound better. Merging

**Comment by mattburman** [comment]
proud of you cg forever defending our rights @cgmcintyr

**Pull request merged**
